version: '3.9'

services:
  db:
    image: mongo
    ports:
      - ${DB_PORT}:8081
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}