version: '3.9'

services:
  db:
    image: mongo
    ports:
      - ${DB_PORT}:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
     - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    restart: always