version: '3.9'

services:
  db:
    image: mongodb:alpine
    ports:
      - ${DB_PORT}:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}